services:
  app-back-blue:
    image: ghcr.io/${GHCR_OWNER}/cloudnative-backend:${IMAGE_TAG}
    container_name: app-back-blue
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - COLOR=blue
      - VERSION=${IMAGE_TAG}
    networks:
      - app-net

networks:
  app-net:
    external: true