services:
  app-back-green:
    image: ghcr.io/${GHCR_OWNER}/cloudnative-backend:${IMAGE_TAG}
    container_name: app-back-green
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - COLOR=green
      - VERSION=${IMAGE_TAG}
    networks:
      - app-net

networks:
  app-net:
    external: true