global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["monitoring-prometheus:9090"]

  - job_name: "backend"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "app-back-blue:3000"
          - "app-back-green:3000"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["monitoring-cadvisor:8080"]

  - job_name: "backend-health"
    metrics_path: /healthz
    static_configs:
      - targets:
          - "app-back-blue:3000"
          - "app-back-green:3000"